### ISSUE TITLE
Undefined symbol: luaL_openlib

### ISSUE THREAD

**Issue by lukeacat** [leafo/lua-enet#20]
kuteshi@universe-1 ~/lol % lua server.lua            
lua: error loading module 'enet' from file '/usr/local/lib/lua/5.3/enet.so':
        /usr/local/lib/lua/5.3/enet.so: undefined symbol: luaL_openlib
stack traceback:
        [C]: in ?
        [C]: in function 'require'
        server.lua:1: in main chunk
        [C]: in ?
kuteshi@universe-1 ~/lol %

**Comment by les-citrons** [comment]
what was the problem? how is this solved?
